name: Context testing
on: [pull_request]

jobs:
  dump_contexts_to_log:
    runs-on: ubuntu-latest
    steps:
      - name: Dump GitHub context
        id: github_context_step
        run: echo '${{ toJSON(github) }}'
      - name: Dump job context
        run: echo '${{ toJSON(job) }}'


name: telegram message
on: [pull_request]
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: send telegram message on push
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          message: |
            ${{ github.actor }} opened a PR in:           
            Repository: ${{ github.repository }}
            ${{github.pull_request}}

            ${{github.event.pull_request}}
            
            See changes: https://github.com/${{ github.repository }}/commit/${{github.sha}}